name: Dagger on Northflank (QEMU) - Remote Engine

on:
  workflow_call:
    inputs:
      function:
        description: "Dagger function"
        type: string
        required: true
      timeout:
        description: "Timeout if not finished after this many minutes"
        type: number
        default: 10
        required: false

jobs:
  remote-dagger-engine:

    if: ${{ github.repository == 'nf-testing/dagger' }}
    runs-on:
      - nf-n4-hc-80-hb-max-upstream
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: ${{ inputs.function }}
        uses: ./.github/actions/call-ci-alt-runner
        with:
          function: ${{ inputs.function }}
      - name: ${{ inputs.function }} (CACHE TEST)
        uses: ./.github/actions/call-ci-alt-runner
        with:
          function: ${{ inputs.function }}
